### ISSUE TITLE
Plugin not start/available

### ISSUE THREAD

**Issue by fvinci** [ouun/zammad-wp#21] opened 2021-09-18 14:04 UTC
This plugin could be very useful for me, but i can't get it to start.
When I insert in the wp-config file the directive: ZAMAMD_URL it also obscures the wordpress management console.
Can you help me?
thanks

**Comment by ouun** [comment] 2021-09-19 08:54
Hi @fvinci,
can you please post here what exactly you put into `wp-config.php` and what you mean by 

> it also obscures the wordpress management console

Also is there a /vendor folder in your plugin folder? If not you need to download the compiled ZIP from here: https://github.com/ouun/zammad-wp/releases/tag/v0.8.3

**Comment by ouun** [comment] 2021-09-29 11:55
Closing this as I did not receive an answer. @fvinci please feel free to reopen if the issue is not solved.

**Closed by ouun** 2021-09-29 11:55 UTC
